Merge branch 'OpenViX/Developer' into atefganm/Developer
cherry pick -> https://github.com/OpenViX/enigma2

diff --git a/tools/enigma2.sh.in b/tools/enigma2.sh.in
--- a/tools/enigma2.sh.in
+++ b/tools/enigma2.sh.in
@@ -118,24 +118,24 @@ if grep -q 'config\.crash\.enabledebug=True' @sysconfdir@/enigma2/settings; then
 # Generate a random message for the logger to know that enigma2 has
 # ended
 #
-    unem="Enigma2 is LEAVING: $RANDOM"
+	unem="Enigma2 is LEAVING: $RANDOM"
 
 # ========== Start of log functions ==========
 # fixup_log() - remove any partial-line at the end a logfile as we
 # switch and add a note there instead.
 #
-    fixup_log() {
-        old="$1"
-        new="$2"
+	fixup_log() {
+		old="$1"
+		new="$2"
 
 # Remove the fsize limit, so we can add the continuation tag.
 # We're in a subprocess and exit when done, so this won't affect
 # restricting the active log file
 #
-        ulimit -S -f unlimited
+		ulimit -S -f unlimited
 
 # An in-line python script...
-        python - "$old" "$new" <<EOP
+		python - "$old" "$new" <<EOP
 import sys, os
 
 ofile = sys.argv[1]
@@ -153,168 +153,168 @@ pos = size - (size % 1024)
 # at the start of the next log, after the note of the preceding log.
 #
 with open(ofile, "r+b") as f:
-    while pos >= 0:
-        f.seek(pos)
-        buf = f.read(1024)
-        where = buf.rfind(b"\n")
-        if where < 0:
-            pos -= 1024
-            continue
+	while pos >= 0:
+		f.seek(pos)
+		buf = f.read(1024)
+		where = buf.rfind(b"\n")
+		if where < 0:
+			pos -= 1024
+			continue
 # OK, we've found the last newline
 # seek there and truncate
 #
-        f.seek(pos + where + 1)
-        f.truncate()
+		f.seek(pos + where + 1)
+		f.truncate()
 # Now add the note as to where future logging has gone
 #
-        f.write(b"Continued in %s\n" % bytes(nfile, "UTF8"))
-        break
+		f.write(b"Continued in %s\n" % bytes(nfile, "UTF8"))
+		break
 EOP
-    }
+	}
 
 # new_log() - open a new log and, if this is a restart, note the
 # next/prev logs pathnames at the end/start of the relevant logs
 #
-    new_log() {
-        if [ -n "$logname" ]; then
-            prev=$logname
-        else
-            prev=
-        fi
-        logname="${debug_dir}/Enigma2_debug_`date +%Y-%m-%d_%H-%M-%S`.log"
-        exec > $logname 2>&1    # Open the new one
+	new_log() {
+		if [ -n "$logname" ]; then
+			prev=$logname
+		else
+			prev=
+		fi
+		logname="${debug_dir}/Enigma2_debug_`date +%Y-%m-%d_%H-%M-%S`.log"
+		exec > $logname 2>&1    # Open the new one
 # If we have opened a new one then we wish to record what the previous
 # one was and also to remove any partial-line at the end of the old log
 # and note the new logname there instead.
 # We do this in the background so that we can get on with logging.
 #
-        if [ -n "$prev" ]; then
-            fixup_log "$prev" "$logname"&
-            echo "Continued from $prev"
-            logswitched=0
-        else
-            logswitched=1
-        fi
-    }
+		if [ -n "$prev" ]; then
+			fixup_log "$prev" "$logname"&
+			echo "Continued from $prev"
+			logswitched=0
+		else
+			logswitched=1
+		fi
+	}
 
 # Set a new file-size limit
 # We MUST ensure that this is ONLY set for the dblogger - NOT enigma2!!!
 # ulimit uses 1024-byte units, so we must multiply the configured limit
 # (in MB) by 1024
 #
-    new_limit() {
-        lim=$(($1 * 1024))
-        ulimit -S -f $lim
-    }
+	new_limit() {
+		lim=$(($1 * 1024))
+		ulimit -S -f $lim
+	}
 
 # dblogger - the main function. This receives the log text on
 # stdout
 #
-    dblogger() {
+	dblogger() {
 
 # We want the logger to ignore TERM, so that if a reboot command is run
 # from the command line this doesn't get booted out before enigma2
 # closes down.
 # We'll exit when enigma2 does anyway (the "read line" will fail).
 #
-        trap "" SIGTERM
+		trap "" SIGTERM
 
-        logname=
-        lim=
-        logswitched=0
-        debug_dir="/home/root/logs"
+		logname=
+		lim=
+		logswitched=0
+		debug_dir="/home/root/logs"
 
 # We look for config.crash.debugloglimit in settings
 # (default == 4, see Screens/LogManager.py) and use it:
 #
-        debugloglimit=`awk -F= '
+		debugloglimit=`awk -F= '
  BEGIN{res=4};
  $1 == "config.crash.debugloglimit" {res=$2; exit};
  END{print res}' @sysconfdir@/enigma2/settings`
 
-        new_limit $debugloglimit
+		new_limit $debugloglimit
 
 # We look for config.crash.debug_path in settings
 # (default == /home/root/logs/, see Screens/LogManager.py) and use it:
 #
-        raw=`awk -F= '
+		raw=`awk -F= '
  BEGIN{res="/home/root/logs/"};
  $1 == "config.crash.debug_path" {res=$2; exit};
  END{print res}' @sysconfdir@/enigma2/settings`
-        debug_dir=${raw%/}      # Strip trailing / if there.
-        trap new_log SIGXFSZ    # Re-opener
-        new_log                 # First opener
+		debug_dir=${raw%/}      # Strip trailing / if there.
+		trap new_log SIGXFSZ    # Re-opener
+		new_log                 # First opener
 
 # The values will be reported at start-up, but we've already read and
 # handled them above, so set flags to ignore them the first time.
 #
-        first_limit=1   # Not yet seen
-        first_lpath=1   # Not yet seen
+		first_limit=1   # Not yet seen
+		first_lpath=1   # Not yet seen
 
-        echo "========== Enigma2 log starts =========="
-        while read -r line; do      # -r == no slash-escaping of input
-            case "$line" in
+		echo "========== Enigma2 log starts =========="
+		while read -r line; do      # -r == no slash-escaping of input
+			case "$line" in
 # Are we being told that enigma2 has exited?
 # If so, we exit too
 #
-            $unem)
-                echo "enigma2 has exited"
-                break
-                ;;
+			$unem)
+				echo "enigma2 has exited"
+				break
+				;;
 # Have we been asked to change the limit or log path?
 # If so, activate the change.
 # We'll log the CHANGE line as well....
 #
-            CHANGE\ config.crash.debugloglimit=*)
-                if [ $first_limit -eq 1 ]; then
-                    first_limit=0
-                else
-                    debugloglimit=`echo $line |
-                         sed -e's/^.*config.crash.debugloglimit=//'`
-                    new_limit $debugloglimit
-                fi
-                ;;
-            CHANGE\ config.crash.debug_path=*)
-                if [ $first_lpath -eq 1 ]; then
-                    first_lpath=0
-                else
-                    raw=`echo $line |
-                         sed -e's/^.*config.crash.debug_path=//'`
-                    debug_dir=${raw%/}      # Strip trailing / if there.
-                    new_log
+			CHANGE\ config.crash.debugloglimit=*)
+				if [ $first_limit -eq 1 ]; then
+					first_limit=0
+				else
+					debugloglimit=`echo $line |
+						 sed -e's/^.*config.crash.debugloglimit=//'`
+					new_limit $debugloglimit
+				fi
+				;;
+			CHANGE\ config.crash.debug_path=*)
+				if [ $first_lpath -eq 1 ]; then
+					first_lpath=0
+				else
+					raw=`echo $line |
+						 sed -e's/^.*config.crash.debug_path=//'`
+					debug_dir=${raw%/}      # Strip trailing / if there.
+					new_log
 # new_log() will set logswitched, but we don't want to rewrite this line
 # for this case, so unset it
 #
-                    logswitched=0
-                fi
-                ;;
-            esac
-            echo "$line"
-            if [ $logswitched -eq 1 ]; then # New log opened
-                echo "$line"                # Write full line into new log
-                logswitched=0
-            fi
-        done
+					logswitched=0
+				fi
+				;;
+			esac
+			echo "$line"
+			if [ $logswitched -eq 1 ]; then # New log opened
+				echo "$line"                # Write full line into new log
+				logswitched=0
+			fi
+		done
 
 # enigma2 has left.
 # As we leave, lift the limit (so we don't potentially create a
 # new log just to record the closing) and record this.
 #
-        ulimit -S -f unlimited
-        echo "========== Enigma2 log ends =========="
-    }
+		ulimit -S -f unlimited
+		echo "========== Enigma2 log ends =========="
+	}
 # ========== End of log functions ==========
 
 # Run into a logging function in such a way that when
 # enigma2 exits the logger exits too.
 # We need to get the exit code from enigma2, not the logger
 #
-        ( LD_PRELOAD=$LIBS @bindir@/enigma2 # run enigma2
-            xstat=$?                        # its exit code
-            echo                            # in case of mid-line crisis
-            echo $unem                      # marker to end logger
-            exit $xstat                     # exit code for this "block"
-        ) 2>&1 | dblogger
+		( LD_PRELOAD=$LIBS @bindir@/enigma2 # run enigma2
+			xstat=$?                        # its exit code
+			echo                            # in case of mid-line crisis
+			echo $unem                      # marker to end logger
+			exit $xstat                     # exit code for this "block"
+		) 2>&1 | dblogger
 	ret=${PIPESTATUS[0]}    # enigma2 exit code, not dblogger's
 else
 	# if debug logs are disabled
@@ -376,6 +376,7 @@ case $ret in
 		/sbin/reboot
 		;;
 	3)
+		rm -fR /home/root/.cache/gstreamer-1.0
 		rm -f /tmp/.listen.camd.socket.ignore
 		;;
 	12)
@@ -387,6 +388,12 @@ case $ret in
 			echo "rescue" > /proc/stb/fp/boot_mode
 		fi
 		/sbin/reboot
+		;;
+	15)
+		rm -fR /home/root/.cache/gstreamer-1.0
+		rm -f /tmp/.listen.camd.socket.ignore
+				dd if=/dev/zero of=/dev/fb0
+		/usr/bin/kodi
 		;;
 	16)
 		if [ -e /proc/stb/info/model ]; then
